version: '3'

services:
  api:
    container_name: aws-api
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=awsuser
      - DB_PASSWORD=awspass
      - DB=aws
    working_dir: /app
    command: npm start
    ports:
      - '8080:8080'
    networks:
      - aws-mentorship-network

  postgres:
    container_name: aws-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=awsuser
      - POSTGRES_PASSWORD=awspass
      - POSTGRES_DB=aws
    networks:
      - aws-mentorship-network
    volumes:
      - aws-mentorship-pgdata:/var/lib/postgresql/data

networks:
  aws-mentorship-network:
    driver: bridge

volumes:
  aws-mentorship-pgdata:
